# This is a basic workflow to help you get started with Actions

name: Deploy to Env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    env:
      RG_Name: RG20-DEV
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_DEV_CREDS}}
      - name: create RG
        uses: azure/cli@v1
        with:
          inlineScript: |
            az account set --subscription be205155-02f7-40e6-b005-1faca67f9160
            az group create --location WestEurope --name ${{env.RG_Name}}
        
      - name: deploy sa
        uses: azure/arm-deploy@v1
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.RG_Name}}
          template: ./storage.bicep

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment: production
    env:
      RG_Name: RG30-PROD
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_PROD_CRED}}
      - name: create RG
        uses: azure/cli@v1
        with:
          inlineScript: |
            az account set --subscription be205155-02f7-40e6-b005-1faca67f9160
            az group create --location WestEurope --name ${{env.RG_Name}}
        
      - name: deploy sa
        uses: azure/arm-deploy@v1
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.RG_Name}}
          template: ./storage.bicep

      - name: deploy sa container
        uses: azure/arm-deploy@v1
        id: deploy-sa-container
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.RG_Name}}
          template: ./blobcontainer.bicep
          parameters: mysaname=${{steps.deploy-sa.outputs.mysaname}}